### ISSUE TITLE
API passing issue.

### ISSUE THREAD

**Issue by ghost** [CPScript/Spam-Call#1]
Fear this API sucks ass..... Fix it :3

**Comment by 0u44** [comment]
Kira, I physically can't because I got no computer... Plus, this was in early development, I barely worked on this

**Comment by ghost** [comment]
> Kira, I physically can't because I got no computer... Plus, this was in early development, I barely worked on this

Skill Issue :3

**Comment by ghost** [comment]
Planned pull request to fix API issue. Moving over to proxied system.

**Comment by 0u44** [comment]
😭🙏
